---
title: "bigram_plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
library(tidytext)
library(stringr)
library(ggraph)
library(igraph)
source("text_analysis_functions.R")

twitter_merged_noRT <- read.csv("twitter_merged_noRT.csv", stringsAsFactors = FALSE)
twitter_merged_noRT <- distinct(twitter_merged_noRT)

noRT <- twitter_merged_noRT %>% 
  filter(screen_name != "Pontifex") #remove the pope..

top_100_RT <- twitter_merged_noRT %>% 
  arrange(-retweet_count) %>% 
  head(100)






```

Translation
```{r}

#filter for hindi characters
hindi_tweets <- noRT %>% 
  filter(
  str_detect(text, "[\u0900-\u097F]+"))


#create word list
hindi_terms <- prepare_text(hindi_tweets) %>% 
  filter(
    str_detect(word, "[\u0900-\u097F]+"))


hindi_trans <- read_csv("hindi-translated.csv")





#### Join translated text to original hindi ####

X1 <- 1:nrow(hindi_terms)
hindi_terms$X1 <- X1

translations <- left_join(hindi_terms, hindi_trans, by = 'X1')

# select only hindi and english, and clean the translation
trans <- translations %>% 
  select(-n, -X1) %>% 
  mutate(word.y = str_replace_all(word.y, '"', ""))
#rename columns
names(trans) <- c("hindi","en")


noRT_trans <- translate_hindi(noRT)

```


### Full dataset (noRT)
- bigrams set to >120
```{r, echo=F, fig.width=12}
####full dataset####
noRT_bigram <- create_bigram(noRT, "", group = TRUE, stem = TRUE) # `group = T` groups terms into umbrella terms
gram_network(noRT_bigram,120)

```
  
  #### translated
```{r,echo=F, fig.width=12}
bigram_trans <- create_bigram(noRT_trans, "", group = TRUE, stem = TRUE)
gram_network(bigram_trans,120)
```
  
  ***  
    
  
          
### filtered for "soil health"
- bigrams set to >100
```{r, echo=F, fig.width=12}
###soil
soil_bigram <- create_bigram(noRT, "soil health", group = T, stem = T)
gram_network(soil_bigram, 80)



```
  
#### translated
```{r,echo=F, fig.width=12}
#### same thing for translated
soil_bigram_translated <- create_bigram(noRT_trans, "soil health", group = T, stem = T)
gram_network(soil_bigram_translated, 80)
```
  
  ***  
  
### filtered for "rangeland health"
- # of bigrams set to >1
```{r, echo=F, fig.width=12}
###rangeland
range_bigram <- create_bigram(noRT, "rangeland health", group = T, stem = T)
gram_network(range_bigram, 1)
```
  
  ***  
  
### filtered for "forest health"
- not very informative 
```{r,include=F, echo=F, fig.width=12}
###forest
forest_bigram <- create_bigram(noRT, "forest health", group = T, stem = T)
gram_network(forest_bigram, 0)
```
  
    
    
***
***
***

## top 100 RT  
  
  
### filtered for "soil"
- # of bigrams set to >2
```{r, echo=F, fig.width=12}
###soil
soil_100_bigram <- create_bigram(top_100_RT, "soil", group = T, stem = T)
gram_network(soil_100_bigram, 2)
```
  
  ***  
  
### filtered for "rangeland"
- no hits
```{r, echo=F, fig.width=12}
###rangeland
# range_100_bigram <- create_bigram(top_100_RT, "rangeland")
# gram_network(range_bigram, 1)
```
  
  ***  
  
### filtered for "forest"
- # of bigrams set to >0
```{r,include=F, echo=F, fig.width=12}
###forest
forest_100_bigram <- create_bigram(top_100_RT, "forest", group = T, stem = T)
gram_network(forest_100_bigram, 0)
```
