---
title: "decay"
author: "Meilin"
date: "8/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(tidyverse)
library(tidytext)
library(stringr)
library(ggraph)
library(igraph)
library(tm)
library(NLP)
library(quanteda)
library(lubridate)
library(dplyr)
library(ggplot2)
source("../text_analysis_functions.R")

# load data
noRT <- read.csv("/home/shares/soilcarbon/Twitter/Merged_v2/twitter_merged_noRT_v2.csv", stringsAsFactors = FALSE)
RT <- read.csv("/home/shares/soilcarbon/Twitter/Merged_v2/twitter_merged_v2.csv",stringsAsFactors = FALSE)
```


```{r, include=FALSE}
#function clean data to remove numbers, usernames, websites, non-ASCII characters and outlier
clean_data <- function(input){
  #input_clean <- removeNumbers(input$text)
  input_clean <- gsub("@\\w+","",input$text)
  input_clean <- gsub(" ?(f|ht)tp(s?)://(.*)[.][a-z]+", "", input_clean)
  input_clean <- gsub("#\\s+","", input_clean)
  input_clean <- gsub("amp", "", input_clean)
  input_clean <- gsub("[^\x01-\x7F]", "", input_clean)

  input$text <- input_clean
  input <- input %>% 
  filter(source != "Twittascope") 

  # to remove the pope
  input <- input %>%
    arrange(-retweet_count) %>%
    filter(screen_name != "Pontifex")

  # to remove all india related tweets
  input_india <- flag_india(input)
  input_no_india <- input_india %>% 
    filter(is_india == 0) 
  
  return(input_no_india)
}
```

### noRT dataset
```{r}
noRT_no_india <- clean_data(noRT)
RT_no_india <- clean_data(RT)
```

### select the SHS 2019 conference
```{r}
# select tweets with hashtag
# #SoilSummit19

input <- noRT_no_india

# SoilSummit19 is used by three conferences (Soil Health Summit 19, TCM Soil Summit, Red River Soil Health Summit)
SHS19 <- input %>% 
  filter(str_detect(tolower(text), "soilsummit19"))
SHS19$conference <- "SHS19"

# the five most retweeted tweets
SHS19_top5 <- SHS19 %>% arrange(-retweet_count) %>% head(5)
# select the RT of SHS19
SHS19_RT <- RT_no_india %>% filter(str_detect(tolower(text), "soilsummit19"))
SHS19_RT <- SHS19_RT %>% filter (is_retweet == TRUE)
SHS19_RT <- SHS19_RT  %>% filter (retweet_count > 0)

# select the RT of the top five
SHS19_RT_top5 <- SHS19_RT %>% filter(retweet_count >= 8) %>% filter(is_retweet == T)

```

```{r}
# barplot to show time series on retweet counts
ggplot(SHS19, aes(y = retweet_count, x = date(created_at), fill = conference)) + 
  geom_bar(stat = "identity") + ggtitle('Soil Health Summit 2019 Tweets')
```

```{r}
# barplot to show time series on total tweets counts
SHS19$date <- date(SHS19$created_at)

Event_19 <- data.frame(SHS19$date, SHS19$conference)
names(Event_19) <- c("date","Conference")

#count value based on week and query words
library(plyr)
counts.df <- ddply(Event_19, .(Event_19$date, Event_19$Conference), nrow)
names(counts.df) <- c("Date", "Conference", "Freq")

ggplot(counts.df, aes(y = Freq, x = Date, fill = Conference)) + 
  geom_bar(stat = "identity") + ggtitle('Number of Tweets on SHS 2019')
```

### select the 5 most retweeted tweets overall
### across all search terms

```{r}
# write a function to find retweet and plot decay for certain tweet based on retweet count rank
library(plyr)

find_rt <- function(rank, noRT_dataset, RT_dataset) {
  result_rt <- RT_dataset %>% 
    filter(substring(RT_dataset$text, 1, 30) == substring(noRT_dataset$text[rank], 1, 30))
  result.df <- ddply(result_rt, .(date(result_rt$created_at), result_rt$query), nrow)
  names(result.df) <- c("Date", "Query", "Number")
  result.df$time_since <- result.df$Date - date(noRT_dataset$created_at[rank])
  result.df$content <- substring(result_rt$text[1], 1, 30)
  names(result.df) <- c("Date", "Query", "Number", "Time_since", "Content")
  return(result.df)
}
```

```{r}
# combine the top five retweets and plot
first <- find_rt(1, noRT_no_india, RT_no_india)
second <- find_rt(2, noRT_no_india, RT_no_india)
third <- find_rt(3, noRT_no_india, RT_no_india)
fourth <- find_rt(4, noRT_no_india, RT_no_india)
fifth <- find_rt(5, noRT_no_india, RT_no_india)

top5 <- rbind(first, second, third, fourth, fifth)
# filtering the data frame by number > 10 to avoid long tail
top5 <- top5 %>% 
  filter(top5$Number > 13)
ggplot(top5, aes(x = Time_since, y = Number, color = Content)) +  geom_line()
```

```{r}
# select one retweet and plot

single_decay <- function(num) {
  test_rt <- SHS19_RT %>% 
    filter(substring(SHS19_RT$text, 1, 30) == substring(SHS19$text[num], 1, 30)) %>% arrange(created_at)
  test_rt$time_since <- round(difftime(test_rt$created_at, test_rt$created_at[1], units = "hours"),0)
  test_rt.df <- ddply(test_rt,.(test_rt$time_since, substring(test_rt$text, 1, 30)), nrow)
  names(test_rt.df) <- c("Time", "Content", "Number")
  #test_rt.df <- test_rt.df %>% filter(test_rt.df$Number > 5)
  return(test_rt.df)
}

```

```{r}
rank1 <- single_decay(1)
ggplot(rank1, aes(x = Time, y = Number)) + geom_line() + 
  labs(x = "Time [Hours]", y = "Total Number of Retweets") +
  ggtitle("top 1 tweet")

rank2 <- single_decay(2)
ggplot(rank2, aes(x = Time, y = Number)) + geom_line() + 
  labs(x = "Time [Hours]", y = "Total Number of Retweets") +
  ggtitle("top 2 tweet")

rank3 <- single_decay(3)
ggplot(rank3, aes(x = Time, y = Number)) + geom_line() + 
  labs(x = "Time [Hours]", y = "Total Number of Retweets") +
  ggtitle("top 3 tweet")

```


```{r}
SHS19_first <- head(SHS19_RT,10) %>% arrange(created_at)

SHS19_first$time_since <- round(difftime(SHS19_first$created_at, SHS19_first$created_at[1], units = "hours"),0)
SHS19_first.df <- ddply(SHS19_first, .(SHS19_first$time_since, SHS19_first$query), nrow)
  names(SHS19_first.df) <- c("Time", "Query", "Number")

ggplot(SHS19_first.df, aes(x = Time, y = Number)) + geom_point()
```

-------------------------------------------------------
### Network Diagram
```{r}
# select input
tt <- data.frame(SHS19_RT$text, SHS19_RT$screen_name)
names(tt) <- c("text", "retweet_user")
tt$author <- SHS19$screen_name[match(tt$text, SHS19$text)]

network <- tt %>% filter(tt$author != "NA")
```

# tweet/RT user network visualization
```{r}
# generate node list
authors <- network %>% distinct(author) 
names(authors) <- "label"
retweet_users <- network %>% distinct(retweet_user) 
names(retweet_users) <- "label"

nodes <- rbind(authors, retweet_users)
nodes <- nodes %>% distinct(label) #to get rid of duplicates in both authors and retweet user
nodes <- nodes %>% rowid_to_column("id")

# generate edge list
library(plyr)
per_route <- ddply(network, .(network$author, network$retweet_user), nrow)
names(per_route) <- c("authors", "retweet_users", "weight")

edges <- per_route %>% left_join(nodes, by = c("authors" = "label"))
colnames(edges)[4] <- "from"
edges <- edges %>% 
  left_join(nodes, by = c("retweet_users" = "label"))
colnames(edges)[5] <- "to"

edges <- select(edges, from, to, weight)
edges
```
```{r}
# interactive plot
library(visNetwork)
library(networkD3)

graph <- graph.data.frame(edges, directed = T)
edges$value <- edges$weight
degree_value <- degree(graph, mode = "in")
nodes$value <- degree_value[match(nodes$id, names(degree_value))]

visNetwork(nodes, edges)
```

```{r}
# network ßdiagram with direction
visNetwork(nodes, edges) %>% 
  visIgraphLayout(layout = "layout_with_fr") %>% 
  visEdges(arrows = "middle")
```

# static network diagram
```{r, fig.width= 16, fig.height= 12}
# ggraph packages to show network diagram
library(tidygraph)
library(ggraph)

routes_tidy <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE)

routes_tidy %>% 
  activate(edges) %>% 
  arrange(desc(weight))

ggraph(routes_tidy, layout = "graphopt") + 
  geom_node_point(aes(size = value)) +
  geom_edge_link(aes(width = weight), alpha = 0.8) + 
  scale_edge_width(range = c(0.1, 0.5)) +
  geom_node_text(aes(label = label), label.size = 0.25, repel = TRUE) +
  labs(edge_width = "Number") +
  theme_graph()

```



