---
title: "bigram_plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
library(tidytext)
library(stringr)
library(ggraph)
library(igraph)


twitter_merged_noRT <- read.csv("twitter_merged_noRT.csv", stringsAsFactors = FALSE)
twitter_merged_noRT <- distinct(twitter_merged_noRT)
noRT <- twitter_merged_noRT %>% 
  filter(screen_name != "Pontifex") #remove the pope..

```


### Full dataset (noRT)
```{r, echo=F, fig.width=12}
####full dataset####
noRT_bigram <- create_bigram(noRT, "")
gram_network(noRT_bigram,100)
```
  
  ***  
    
  
          
### filtered for "soil health"
```{r, echo=F, fig.width=12}
###soil
soil_bigram <- create_bigram(noRT, "soil health")
gram_network(soil_bigram, 100)
```
  
  ***  
  
### filtered for "rangeland health"
```{r, echo=F, fig.width=12}
###rangeland
range_bigram <- create_bigram(noRT, "rangeland health")
gram_network(range_bigram, 1)
```
  
  ***  
  
### filtered for "forest health"
```{r, echo=F, fig.width=12}
###forest
forest_bigram <- create_bigram(noRT, "forest health")
gram_network(forest_bigram, 0)
```
