---
title: "communities"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=10) 
```

This code explores communites, based on different slices of the

```{r}
library(plyr)
library(tidyverse)
library(tidytext)
library(stringr)
library(tidygraph)
library(igraph)
library(ggraph)
source("../../text_analysis_functions.R")

# load data
noRT <- read.csv("/home/shares/soilcarbon/Twitter/Merged_v3/twitter_merged_noRT_v3.csv", stringsAsFactors = FALSE)
RT <- read.csv("/home/shares/soilcarbon/Twitter/Merged_v3/twitter_merged_v3.csv",stringsAsFactors = FALSE)

RT_clean <- clean_data(RT, rm_pope = T, rm_india = T)
noRT_clean <- clean_data(noRT, rm_pope = T, rm_india = T)

coded <- read_csv("top_user_coded.csv")

```

### functions
```{r}
create_network <- function(users) {
  
  
  ## get tweets from desired users
  selected_tweets <- noRT_clean %>% 
  filter(screen_name %in% users$screen_name) %>% 
  select(text, screen_name) %>% 
  dplyr::rename("author" = "screen_name")

# filter down the the full RT dataset
retweets <- RT_clean%>% 
  dplyr::filter(is_retweet == TRUE & retweet_count > 1) %>% 
  dplyr::select(screen_name, text)

# join together by text, this should give us all retweet instances of each author
joined <- dplyr::left_join(retweets, selected_tweets)


network <- dplyr::filter(joined, !is.na(author))

# label distinct authors and retweeters to create nodes
authors <- network %>% dplyr::distinct(author) 
names(authors) <- "label"
retweet_users <- network %>% dplyr::distinct(screen_name) 
names(retweet_users) <- "label"


nodes <- rbind(authors, retweet_users)
nodes <- nodes %>% distinct(label) #to get rid of duplicates in both authors and retweet user
nodes <- nodes %>% rowid_to_column("id")

# generate edge list
per_route <- ddply(network, .(network$author, network$screen_name), nrow)
names(per_route) <- c("label", "retweet_users", "weight")

edges <- per_route %>% 
  dplyr::left_join(nodes)

colnames(edges)[4] <- "from"
edges <- edges %>% 
  left_join(nodes, by = c("retweet_users" = "label"))
colnames(edges)[5] <- "to"

edges <- dplyr::select(edges, from, to, weight)



tidy_graph <- tbl_graph(nodes = nodes, edges = edges, directed = FALSE)



  
return(tidy_graph)

}

graph_community <- function(community) {
      ggraph(community, layout = "graphopt") + 
      geom_node_point(aes(col = factor(community))) +
      geom_edge_link(aes(width = weight), alpha = 0.5) + 
      scale_edge_width(range = c(0.1, 0.5)) +
      geom_node_label(aes(label= node_label, 
                          size= node_size, 
                          col = factor(community)),
                      label.size=0, 
                      fill="white", 
                      segment.colour="slateblue",
                      color="black", 
                      repel=TRUE, 
                      fontface="bold", 
                      show.legend = FALSE) +
      labs(edge_width = "Number") +
      theme_graph()
}
```


##rangeland network
```{r}
lab_limit <- 50

users <- noRT_clean %>% 
  arrange(desc(retweet_count)) %>% 
  filter(str_detect(query, "rangeland")) %>% 
  head(100)

### create network
network <- create_network(users)

### calc centrality, find communities and set label limits for graph
## i decided to do this outside of the function so we could explore how different degree and centrality algorithms affect our results
centrality <- network %>% 
  dplyr::mutate(centrality = centrality_degree(weights = weight)) %>% 
  dplyr::mutate(community = group_fast_greedy(weights = weight)) %>%
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))
 
centrality_info <- network %>% 
  dplyr::mutate(centrality = centrality_degree(weights = weight)) %>% 
  dplyr::mutate(community = group_infomap(weights = weight)) %>%
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))
 
                
##graph               
graph_community(centrality)
graph_community(centrality_info)

```

```{r}
lab_limit <- 250

users <- noRT_clean %>% 
  arrange(desc(retweet_count)) %>% 
  filter(str_detect(query, "regen")) %>% 
  head(50)


network <- create_network(users)

centrality <- network %>% 
  dplyr::mutate(centrality = centrality_degree(weights = weight)) %>% 
  dplyr::mutate(community = group_fast_greedy(weights = weight)) %>%
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))
 
centrality_info <- network %>% 
  dplyr::mutate(centrality = centrality_degree(weights = weight)) %>% 
  dplyr::mutate(community = group_infomap(weights = weight)) %>%
  dplyr::arrange(centrality) %>% 
  dplyr::mutate(ranking = row_number()) %>% 
  dplyr::top_n(500, centrality) %>% 
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))
 
                
##graph               
#graph_community(centrality)
graph_community(centrality_info)
```

```{r}
lab_limit <- 250

users <- coded %>% 
  filter(str_detect(type,"farmer"))


network <- create_network(users)

centrality_info <- network %>% 
  dplyr::mutate(centrality = centrality_degree(weights = weight)) %>% 
  dplyr::mutate(community = group_infomap(weights = weight)) %>%
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))

creators <- centrality_info %>% 
  activate(nodes) %>% 
  filter(centrality > 1)

graph_community(creators)
```

```{r}
all_rts <- noRT_clean %>% 
  filter(retweet_count > 0) 

network <- create_network(all_rts)

centrality_info <- network %>% 
  dplyr::mutate(centrality = centrality_degree()) %>% 
  dplyr::mutate(community = group_infomap(weights = weight)) %>%
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))
 

nodes <- as_data_frame(centrality_info, "vertices")     

cent <- nodes %>% 
  arrange(desc(centrality)) %>% 
  dplyr::mutate(ID = row_number())

ggplot(cent, aes(ID, centrality)) +
  geom_col() +
  scale_x_continuous(limits = c(0,1000)) +
  scale_y_continuous(limits = c(0, 6000))

#### investigating discrepancy between centrality and RT
cover_coach <- filter(noRT_clean, screen_name == "CoverCropCoach")

test <- noRT_clean %>% 
  filter(
    str_detect(text, paste(cover_coach$text, collapse = "|"))
  ) 
#### these ^ results are a little confusing... many different authors here with the same tweet, but we are not counting them as retweets... this 

######### create csv of "top users"




```


##### communities of top 1000 user's friends based on updated
```{r}
# get list of all friends for the top 100 users (see )
user_friends <- read_csv("/home/shares/soilcarbon/Twitter/Influencers/user_friends.csv")



#### look only at friends who are present in our dataset
friends_matched <- merge(user_friends, RT_clean[,c("screen_name", "user_id")])
unique <- dplyr::distinct(friends_matched)



network <- unique %>% 
  dplyr::select(user, screen_name) %>% 
  rename("author" = "user")

authors <- network %>% dplyr::distinct(author) 
names(authors) <- "label"
retweet_users <- network %>% dplyr::distinct(screen_name) 
names(retweet_users) <- "label"

nodes <- rbind(authors, retweet_users)
nodes <- nodes %>% distinct(label) #to get rid of duplicates in both authors and retweet user
nodes <- nodes %>% rowid_to_column("id")

# generate edge list
per_route <- ddply(network, .(network$author, network$screen_name), nrow)
names(per_route) <- c("label", "retweet_users", "weight")

edges <- per_route %>% 
  dplyr::left_join(nodes)

colnames(edges)[4] <- "from"
edges <- edges %>% 
  left_join(nodes, by = c("retweet_users" = "label"))
colnames(edges)[5] <- "to"

edges <- dplyr::select(edges, from, to, weight)

##### include only edges of weight >1

edges_weighted <- filter(edges, weight > 1)

tidy_graph <- tbl_graph(nodes = nodes, edges = edges_weighted, directed = FALSE)

lab_limit <- 1



centrality_info <- tidy_graph %>% 
  dplyr::mutate(centrality = centrality_degree(weights = weight)) %>% 
  dplyr::mutate(community = group_infomap(weights = weight)) %>%
  dplyr::mutate(node_label = if_else(centrality > lab_limit, label, "")) %>%
  dplyr::mutate(node_size = if_else(centrality > lab_limit, centrality, 0))


creators <- centrality_info 
# %>% 
#   activate(nodes) %>%
#   filter(centrality > 100)

    ggraph(creators, layout = 'linear', circular = TRUE) +
      geom_edge_arc(alpha=0.05,
                    aes(col = ifelse(weight == 1, "1",
                                     ifelse(weight > 100 & weight <= 500, "1-5", "5+")),
                        edge_width = weight)) +
      geom_node_label(aes(label=node_label,
                          size=node_size,
                          col = factor(community)),
                      label.size=0,
                      fill="#ffffff66",
                      segment.colour="slateblue",
                      color="black",
                      repel=TRUE,
                      fontface="bold",
                      show.legend = FALSE) +
      coord_fixed() +
      scale_size_area(trans="sqrt") +
      theme_graph() +
      guides(edge_width = FALSE,
             edge_colour = guide_legend(title = "Edge weights",
                                        override.aes = list(edge_alpha = 1))) +
      theme(
            plot.title = element_text(size = rel(3)),
            plot.subtitle = element_text(size = rel(2)),
            legend.text = element_text(size = rel(2)))


```





























